const typeHeader = {
  'turning': [{
    caption: '队伍序号',
    type: 'number'
  }, {
    caption: '队伍名称',
    type: 'string'
  }, {
    caption: '队长姓名',
    type: 'string'
  }, {
    caption: '队长学号',
    type: 'string'
  }, {
    caption: '队长专业',
    type: 'string'
  }, {
    caption: '使用语言',
    type: 'string'
  }, {
    caption: '队长手机号',
    type: 'string'
  }, {
    caption: '队长邮箱',
    type: 'string'
  }, {
    caption: '队员1姓名',
    type: 'string'
  }, {
    caption: '队员1学号',
    type: 'string'
  }, {
    caption: '队员1专业',
    type: 'string'
  }, {
    caption: '队员2姓名',
    type: 'string'
  }, {
    caption: '队员2学号',
    type: 'string'
  }, {
    caption: '队员2专业',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }],
  'innovation': [{
    caption: '序号',
    type: 'number'
  }, {
    caption: '问题1',
    type: 'string'
  }, {
    caption: '问题2',
    type: 'string'
  }, {
    caption: '问题3',
    type: 'string'
  }, {
    caption: '问题4',
    type: 'string'
  }, {
    caption: '姓名',
    type: 'string'
  }, {
    caption: '性别',
    type: 'string'
  }, {
    caption: '专业',
    type: 'string'
  }, {
    caption: '学号',
    type: 'string'
  }, {
    caption: '手机号',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }],
  'special': [{
    caption: '序号',
    type: 'number'
  }, {
    caption: '姓名',
    type: 'string'
  }, {
    caption: '性别',
    type: 'string'
  }, {
    caption: '单位',
    type: 'string'
  }, {
    caption: '手机号',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }],
  'turingOnline': [{
    caption: '队伍序号',
    type: 'number'
  }, {
    caption: '队伍名称',
    type: 'string'
  }, {
    caption: '队长姓名',
    type: 'string'
  }, {
    caption: '队长学校',
    type: 'string'
  }, {
    caption: '使用语言',
    type: 'string'
  }, {
    caption: '队长手机号',
    type: 'string'
  }, {
    caption: '队长邮箱',
    type: 'string'
  }, {
    caption: '队员1姓名',
    type: 'string'
  }, {
    caption: '队员1x学校',
    type: 'string'
  }, {
    caption: '队员2姓名',
    type: 'string'
  }, {
    caption: '队员2学校',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }],
  'certreq': [{
    caption: '序号',
    type: 'number'
  }, {
    caption: '队长姓名',
    type: 'string'
  }, {
    caption: '队长手机号',
    type: 'string'
  }, {
    caption: '队长邮箱',
    type: 'string'
  }, {
    caption: '是否需要证书',
    type: 'string'
  }, {
    caption: '队员1姓名',
    type: 'string'
  }, {
    caption: '队员2姓名',
    type: 'string'
  }, {
    caption: '地址省市',
    type: 'string'
  }, {
    caption: '邮编',
    type: 'string'
  }, {
    caption: '详细地址',
    type: 'string'
  }, {
    caption: '备注',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }],
  'turing_feedback': [{
    caption: '序号',
    type: 'number'
  }, {
    caption: '参赛类型',
    type: 'string'
  }, {
    caption: '如何了解到',
    type: 'string'
  }, {
    caption: '专业',
    type: 'string'
  }, {
    caption: '年级',
    type: 'string'
  }, {
    caption: '为何参赛',
    type: 'string'
  }, {
    caption: '难度',
    type: 'string'
  }, {
    caption: '服务不到位',
    type: 'string'
  }, {
    caption: '服务建议',
    type: 'string'
  }, {
    caption: 'OJ 建议',
    type: 'string'
  }, {
    caption: '题目质量',
    type: 'string'
  }, {
    caption: '邮寄证书',
    type: 'string'
  }, {
    caption: '满意度',
    type: 'string'
  }, {
    caption: '继续参加',
    type: 'string'
  }, {
    caption: '提交时间',
    type: 'string'
  }]
}

module.exports = typeHeader
